### ISSUE TITLE
Formular as técnicas de Levantamento de Requisitos

### ISSUE THREAD

**Issue by salgad019** [maluvasc/Gerenciador-videos-IA#10]
1. **Ishikawa**

6 áreas ->
Medidas;
Materiais*;
Métodos (processos);
Ambiente*;
Pessoas;
Máquina.
-> PROBLEMA
 
2. **Mapa Mental**

3. **Entrevista**
Estruturada;
Semi-Estruturada.

**Comment by gabrielnrds** [comment]
**MAPA MENTAL**

Iniciei o mapa mental no Miro, aqui vai o link:
https://miro.com/welcomeonboard/aEVzem01R2ZWd1ZtSzBXNW5uei81bnUrNVY1ajJGNEpmUjl3dWN2ekR1QmpycXhnYW4zWElubjdQWkQ2Ym9hNS82MWNVM0tyaFFNV0RTakt2SEpIeHJMcEE4a0hJTWpFQWhrU283SjQ1NWFSN2V6Nnh6ODRoSk5XYnl1ejl4cFEhZQ==?share_link_id=738438930222

**Comment by salgad019** [comment]
Segue o link do mapa mental:

https://miro.com/app/board/uXjVLCWlptE=/?utm_source=notification&utm_medium=email&utm_campaign=daily-updates&utm_content=view-board-cta&lid=bteej2r6fzsw

**Comment by salgad019** [comment]
Segue o link da espinha de peixe (ishikawa):

https://miro.com/welcomeonboard/WUo0V084R0MyMmZVVWlZRFF6bVBuejl3TThBeWpMQksyR0txQ2NmRkR0bnV4WkpheVRRanVpcm10UkRLZGJDMms4R251bUVGUEFrb1g3VGRicVc1bC9TR3JhTGlxdk1mQklJZUJTUFZtWS82TjNXSzFoSzNCQ1IxcVc5dUpJZUohZQ==?share_link_id=623242428031

**Comment by gabrielnrds** [comment]
Fazer:

1. Roteiro da entrevista
2. Análise da entrevista
